apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-worker-node
spec:
  template:
    metadata:
      name: deploy-worker-node
    spec:
      containers:
      - name: deploy-worker-node
        image: patrocinio/icp-scaling-icp_inception:1.3
        imagePullPolicy: Always
        command: ["/installer/install.sh"]
        env:
          - name: LICENSE
            value: accept
          - name: WORKER
            value: $WORKER
      restartPolicy: Never
