apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-worker-node
spec:
  template:
    metadata:
      name: deploy-worker-node
    spec:
      containers:
      - name: deploy-worker-node
        image: patrocinio/icp-scaling-icp_inception:latest
        imagePullPolicy: Always
        command: ["/installer/install.sh"]
        env:
          - name: LICENSE
            value: accept
          - name: WORKER
            valueFrom:
              configMapKeyRef:
                name: worker-node
                key: worker      
      restartPolicy: Never
