apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-worker-node
spec:
  template:
    metadata:
      name: deploy-worker-node
    spec:
      containers:
      - name: deploy-worker-node
        image: patrocinio/icp-scaling-icp_inception:latest
        imagePullPolicy: Always
        command: ["/installer/installer.sh", "install",  "-l", "10.0.0.4"]
        env:
          - name: LICENSE
            value: accept
      restartPolicy: Never
