apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: worker-node-utilization
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryList: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      name: worker-node-utilization
    spec:
      containers:
      - name: worker-node-utilization
        image: patrocinio/icp-scaling-worker-node-utilization:latest
        imagePullPolicy: Always
      restartPolicy: Never
